sudo: false
language: python
cache: pip
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

install:
  - python setup.py install

before_script:
  # 1) stop the build if there are Python syntax errors or undefined names
  # 2) exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  # - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
      pip install flake8;
      flake8 . --count --exit-zero --select=E901,E999,F821,F822,F823 --show-source --statistics;
      flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics; 
    fi

# command to run tests, e.g. python setup.py test

script:
  # We might like to get out of the source directory before running tests to
  # avoid PYTHONPATH confusion? As an example, see here:
  #     https://github.com/tornadoweb/tornado/blob/master/.travis.yml
  - python setup.py test
